### ISSUE TITLE
Got an error when attempting to open a GlueSessions

### ISSUE THREAD

**Issue by jerrywonggithub** [aws-samples/dbt-glue#229]
### Describe the bug
I was using [Cosmos](https://github.com/astronomer/astronomer-cosmos/tree/main) to orchestrate dbt jobs with dbt-glue and encountered below error mentioned not able to locate credential to create glue session, I checked source code of Cosmos's behavior and found it would initiate subprocess to communicate with Glue, and I have configured iam role arn at dbt profile.yml, however no aws credentials can be located and it should have connected with aws iam role.
Suspecting it could only use ak/sk in env and passing to subprocess?

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

### Expected behavior
Using IAM role 

### Screenshots and log output
[2023-08-29, 04:44:58 UTC] {{taskinstance.py:1768}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 282, in execute
    result = self.build_and_run_cmd(context=context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 194, in build_and_run_cmd
    return self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 185, in run_command
    self.exception_handling(result)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 77, in exception_handling
    raise AirflowException(
airflow.exceptions.AirflowException: ('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m04:44:57  Running with dbt=1.4.6', '\x1b[0m04:44:57  Unable to do partial parsing because config vars, config profile, or config target have changed', '\x1b[0m04:44:57  Unable to do partial parsing because profile has changed', '\x1b[0m04:44:57  Unable to do partial parsing because env vars used in profiles.yml have changed', '\x1b[0m04:44:57  Unable to do partial parsing because a project dependency has been added', '\x1b[0m04:44:58  [\x1b[33mWARNING\x1b[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.', 'There are 2 unused configuration paths:', '- models.dbtgluenyctaxidemo.gold_metrics', '- models.dbtgluenyctaxidemo.silver_metrics', '\x1b[0m04:44:58  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 367 macros, 0 operations, 0 seed files, 1 source, 0 exposures, 0 metrics', '\x1b[0m04:44:58', '\x1b[0m04:44:58  Glue adapter: Got an error when attempting to open a GlueSession : Unable to locate credentials', '\x1b[0m04:44:58  Glue adapter: Got an error when attempting to open a GlueSession : Database Error', '  Unable to locate credentials', '\x1b[0m04:44:58', '\x1b[0m04:44:58  Finished running  in 0 hours 0 minutes and 0.08 seconds (0.08s).', '\x1b[0m04:44:58  Encountered an error:', 'Database Error', '  Got an error when attempting to open a GlueSessions: Database Error', '    Unable to locate credentials')
[2023-08-29, 04:44:59 UTC] {{taskinstance.py:1318}} INFO - Marking task as FAILED. dag_id=my_cosmos_dag_v2, task_id=silver_nyctaxi_avg_metrics.silver_nyctaxi_avg_metrics_run, execution_date=20230829T044451, start_date=20230829T044454, end_date=20230829T044459
[2023-08-29, 04:44:59 UTC] {{standard_task_runner.py:100}} ERROR - Failed to execute job 3 for task silver_nyctaxi_avg_metrics.silver_nyctaxi_avg_metrics_run (('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m04:44:57  Running with dbt=1.4.6', '\x1b[0m04:44:57  Unable to do partial parsing because config vars, config profile, or config target have changed', '\x1b[0m04:44:57  Unable to do partial parsing because profile has changed', '\x1b[0m04:44:57  Unable to do partial parsing because env vars used in profiles.yml have changed', '\x1b[0m04:44:57  Unable to do partial parsing because a project dependency has been added', '\x1b[0m04:44:58  [\x1b[33mWARNING\x1b[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.', 'There are 2 unused configuration paths:', '- models.dbtgluenyctaxidemo.gold_metrics', '- models.dbtgluenyctaxidemo.silver_metrics', '\x1b[0m04:44:58  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 367 macros, 0 operations, 0 seed files, 1 source, 0 exposures, 0 metrics', '\x1b[0m04:44:58', '\x1b[0m04:44:58  Glue adapter: Got an error when attempting to open a GlueSession : Unable to locate credentials', '\x1b[0m04:44:58  Glue adapter: Got an error when attempting to open a GlueSession : Database Error', '  Unable to locate credentials', '\x1b[0m04:44:58', '\x1b[0m04:44:58  Finished running  in 0 hours 0 minutes and 0.08 seconds (0.08s).', '\x1b[0m04:44:58  Encountered an error:', 'Database Error', '  Got an error when attempting to open a GlueSessions: Database Error', '    Unable to locate credentials'); 1230)

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.4.6
  - latest:    1.6.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - spark: 1.4.3  - Update available!
  - glue:  1.4.23 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

**The operating system you're using:**

**The output of `python --version`:**
Python 3.10.9

**Comment by moomindani** [comment]
The error log said `Unable to locate credentials` which means dbt-glue adapter could not refer the AWS credentials as you mentioned.
dbt-glue adapter depends on boto3 (AWS SDK for Python), which refers not only access key/secret key, but also default credential chain defined in https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html.
I would recommend you to check your credential setting.

**Comment by dma-rep092** [comment]
Hi @jerrywonggithub . Did you manage to find a solution? I am facing exactly the same issue in the same conditions.

**Comment by AmineIzanami** [comment]
For those that may face the same problem, the issue here is that dbt glue adapter when creating a boto3 session look for `"default" ` profil, so in your MWAA dag you can set up this with something similar to 
```
import subprocess

subprocess.run(["aws", "configure","set","aws_access_key_id","YOUR_AWS_ACCESS_KEY_ID","--profile","default"])
subprocess.run(["aws", "configure","set","aws_secret_access_key","YOUR_AWS_SECRET_ACCESS_KEY","--profile","default"])
```
there are better ways to do it, but that a quick and dirty way to fix your issue @jerrywonggithub

**Comment by garrett-groff-ch** [comment]
@AmineIzanami  I am running into this error when I try the above solution. What am I missing here??

`[Errno 13] Permission denied: 'aws'`

**Comment by garrett-groff-ch** [comment]
> @AmineIzanami I am running into this error when I try the above solution. What am I missing here??
> 
> `[Errno 13] Permission denied: 'aws'`

Follow-up:  It seems I didn't actually have aws installed in my docker container. Solved!
