### ISSUE TITLE
Exception message is not complete when using glue 3.0

### ISSUE THREAD

**Issue by denys-tyshetskyy** [aws-samples/dbt-glue#294]
### Describe the bug
When I am running glue-run for the glue 3.0 the exception returns very cryptic error message. Message is provided below.

When I switch to glue 2.0, the error becomes way more useful when it says that there is no access to default database and some lake formation permission issues.

### Steps To Reproduce
Delete default glue database and/or remove LakeFormation permissions for the database that you are using in the dbt project.
Try to do dbt run on the pipeline which interacts with tables in the glue database

### Expected behavior
Full error is displayed when glue 3.0 is being used

### Screenshots and log output
_Glue adapter: Glue returned `error` for statement None for code SqlWrapper2.execute('''/* {"app": "dbt", "dbt_version": "1.7.3", "profile_name": "...", "target_name": "dev", "node_id": "..."} */
drop table if exists ...'''), Py4JError: An error occurred while calling o89.toString. Trace:_

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.7.3
  - latest:    1.7.3 - Up to date!

Plugins:
  - glue:  1.7.0 - Up to date!
  - spark: 1.7.1 - Up to date!

```

**The operating system you're using:**
Windows

**The output of `python --version`:**
3.9

**Comment by moomindani** [comment]
Apologizes for delay. This has been reported one year ago and the current latest Glue version is 5.0. I am closing this for now, but please feel free to reopen if you still see the same issue with the latest version of dbt-glue and Glue 5.0.

**Comment by jacksbox** [comment]
I would like to reopen this topic as I ran into the same issue when using glue 4.0

Error message with glue 4.0. This gives me no clear hint of what is going on.

```
Database Error in model stg_source (models/staging/stg_source.sql)
  Glue cursor returned `error` for statement None for code SqlWrapper2.execute('''/* {"app": "dbt", "dbt_version": "1.9.4", "profile_name": "cellforce_dbt_glue", "target_name": "dev", "node_id": "model.cellforce_dbt_glue.stg_source"} */
  drop table if exists limslabguruexperiments_dev_silver_db.stg_source''', use_arrow=False, location='None'), Py4JError: An error occurred while calling o89.toString. Trace:
  java.lang.IllegalArgumentException: object is not an instance of declaring class
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
  	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
  	at py4j.Gateway.invoke(Gateway.java:282)
  	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
  	at py4j.commands.CallCommand.execute(CallCommand.java:79)
  	at py4j.GatewayConnection.run(GatewayConnection.java:238)
  	at java.lang.Thread.run(Thread.java:750)
```

Error message with glue 2.0. This helped me solve the issue.

```
Database Error in model stg_source (models/staging/stg_source.sql)
  Glue cursor returned `error` for statement None for code SqlWrapper2.execute('''/* {"app": "dbt", "dbt_version": "1.9.4", "profile_name": "cellforce_dbt_glue", "target_name": "dev", "node_id": "model.cellforce_dbt_glue.stg_source"} */
  drop table if exists limslabguruexperiments_dev_silver_db.stg_source''', use_arrow=False, location='None'), AnalysisException: 'java.lang.RuntimeException: MetaException(message:Unable to verify existence of default database: com.amazonaws.services.glue.model.AccessDeniedException: User: *** is not authorized to perform: glue:GetDatabase on resource: *** because no identity-based policy allows the glue:GetDatabase action (Service: AWSGlue; Status Code: 400; Error Code: AccessDeniedException; Request ID: ***; Proxy: null));'
```

**Comment by jacksbox** [comment]
I would like to reopen this topic as I ran into the same issue when using glue 4.0

Error message with glue 4.0. This gives me no clear hint of what is going on.

```
Database Error in model stg_source (models/staging/stg_source.sql)
  Glue cursor returned `error` for statement None for code SqlWrapper2.execute('''/* {"app": "dbt", "dbt_version": "1.9.4", "profile_name": "***", "target_name": "dev", "node_id": "model.***.stg_source"} */
  drop table if exists ***.stg_source''', use_arrow=False, location='None'), Py4JError: An error occurred while calling o89.toString. Trace:
  java.lang.IllegalArgumentException: object is not an instance of declaring class
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
  	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
  	at py4j.Gateway.invoke(Gateway.java:282)
  	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
  	at py4j.commands.CallCommand.execute(CallCommand.java:79)
  	at py4j.GatewayConnection.run(GatewayConnection.java:238)
  	at java.lang.Thread.run(Thread.java:750)
```

Error message with glue 2.0. This helped me solve the issue.

```
Database Error in model stg_source (models/staging/stg_source.sql)
  Glue cursor returned `error` for statement None for code SqlWrapper2.execute('''/* {"app": "dbt", "dbt_version": "1.9.4", "profile_name": "***", "target_name": "dev", "node_id": "model.***.stg_source"} */
  drop table if exists ***.stg_source''', use_arrow=False, location='None'), AnalysisException: 'java.lang.RuntimeException: MetaException(message:Unable to verify existence of default database: com.amazonaws.services.glue.model.AccessDeniedException: User: *** is not authorized to perform: glue:GetDatabase on resource: *** because no identity-based policy allows the glue:GetDatabase action (Service: AWSGlue; Status Code: 400; Error Code: AccessDeniedException; Request ID: ***; Proxy: null));'
```
