### ISSUE TITLE
Can't write simple table using Hudi 0.11.0 and Spark 3.1.1 (Glue 3.0)

### ISSUE THREAD

**Issue by henrique0bl** [aws-samples/dbt-glue#42]
### Describe the bug
I'm trying to write a simple table ie. 2 fields 1 bigint and the other string. And after dbt run I get: `org.apache.hudi.exception.HoodieException: 'hoodie.table.name' must be set. ` even the SQL query having the table name.

### Steps To Reproduce
Just tried to write a simple table using Spark 3.1.1 (Glue 3.0) and hudi 0.11.0 (also I tried with 0.10.1 aws and 0.7.0 aws version)

```
{{ config(
    materialized = 'incremental',
    unique_key='id',
    incremental_strategy = 'append',
) }}

{% if not is_incremental() %}

select cast(1 as bigint) as id, 'hello' as msg
union all
select cast(2 as bigint) as id, 'goodbye' as msg

{% else %}

select cast(2 as bigint) as id, 'yo' as msg
union all
select cast(3 as bigint) as id, 'anyway' as msg

{% endif %}
``` 

### Expected behavior
```
/* after running the model twice this should create 4 rows in the table
 * | id | msg     |
 * |----|---------|
 * | 1  | hello   |
 * | 2  | goodbye |
 * | 2  | yo      |
 * | 3  | anyway  |
 */
```

### Screenshots and log output
```
7:41:03.987255 [error] [MainThread]: Database Error in model test_hudi__append (models/test_hudi/test_hudi__append.sql)
17:41:03.987609 [error] [MainThread]:   Glue cursor returned `error` for statement None for code SqlWrapper2.execute('''create table bi_tmp.test_hudi__append
17:41:03.987963 [error] [MainThread]:
17:41:03.988301 [error] [MainThread]:       using hudi
17:41:03.988640 [error] [MainThread]:
17:41:03.988961 [error] [MainThread]:
17:41:03.989302 [error] [MainThread]:       LOCATION 's3://bucket/dbt_glue/data/bi_tmp/test_hudi__append/'
17:41:03.989648 [error] [MainThread]:
17:41:03.990001 [error] [MainThread]:       as
17:41:03.990611 [error] [MainThread]:
17:41:03.991199 [error] [MainThread]:
17:41:03.991647 [error] [MainThread]:   /* after running the model twice this should create 4 rows in the table
17:41:03.992074 [error] [MainThread]:    * | id | msg     |
17:41:03.992496 [error] [MainThread]:    * |----|---------|
17:41:03.992915 [error] [MainThread]:    * | 1  | hello   |
17:41:03.993419 [error] [MainThread]:    * | 2  | goodbye |
17:41:03.993796 [error] [MainThread]:    * | 2  | yo      |
17:41:03.994168 [error] [MainThread]:    * | 3  | anyway  |
17:41:03.994669 [error] [MainThread]:    */
17:41:03.995227 [error] [MainThread]:
17:41:03.995630 [error] [MainThread]:
17:41:03.995983 [error] [MainThread]:
17:41:03.996317 [error] [MainThread]:   select cast(1 as bigint) as id, 'hello' as msg
17:41:03.996639 [error] [MainThread]:   union all
17:41:03.996974 [error] [MainThread]:   select cast(2 as bigint) as id, 'goodbye' as msg
17:41:03.997297 [error] [MainThread]:
17:41:03.997617 [error] [MainThread]:   '''), Py4JJavaError: An error occurred while calling o73.sql.
17:41:03.997939 [error] [MainThread]:   : org.apache.hudi.exception.HoodieException: 'hoodie.table.name' must be set.
17:41:03.998357 [error] [MainThread]:   	at org.apache.hudi.common.config.HoodieConfig.getStringOrThrow(HoodieConfig.java:217)
17:41:03.998743 [error] [MainThread]:   	at org.apache.hudi.HoodieSparkSqlWriter$.write(HoodieSparkSqlWriter.scala:96)
17:41:03.999100 [error] [MainThread]:   	at org.apache.hudi.DefaultSource.createRelation(DefaultSource.scala:163)
17:41:03.999448 [error] [MainThread]:   	at org.apache.spark.sql.execution.datasources.DataSource.writeAndRead(DataSource.scala:530)
17:41:03.999822 [error] [MainThread]:   	at org.apache.spark.sql.execution.command.CreateDataSourceTableAsSelectCommand.saveDataIntoTable(createDataSourceTables.scala:220)
17:41:04.000145 [error] [MainThread]:   	at org.apache.spark.sql.execution.command.CreateDataSourceTableAsSelectCommand.run(createDataSourceTables.scala:177)
17:41:04.000473 [error] [MainThread]:   	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:108)
17:41:04.000833 [error] [MainThread]:   	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:106)
17:41:04.001179 [error] [MainThread]:   	at org.apache.spark.sql.execution.command.DataWritingCommandExec.executeCollect(commands.scala:120)
17:41:04.001508 [error] [MainThread]:   	at org.apache.spark.sql.Dataset.$anonfun$logicalPlan$1(Dataset.scala:229)
17:41:04.001891 [error] [MainThread]:   	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3724)
17:41:04.002221 [error] [MainThread]:   	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
17:41:04.002559 [error] [MainThread]:   	at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:232)
17:41:04.002886 [error] [MainThread]:   	at org.apache.spark.sql.execution.SQLExecution$.executeQuery$1(SQLExecution.scala:110)
17:41:04.003386 [error] [MainThread]:   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:135)
17:41:04.003824 [error] [MainThread]:   	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
17:41:04.004209 [error] [MainThread]:   	at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:232)
17:41:04.004695 [error] [MainThread]:   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:135)
17:41:04.005129 [error] [MainThread]:   	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:253)
17:41:04.005505 [error] [MainThread]:   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:134)
17:41:04.006294 [error] [MainThread]:   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
17:41:04.006685 [error] [MainThread]:   	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:68)
17:41:04.007027 [error] [MainThread]:   	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3722)
17:41:04.007355 [error] [MainThread]:   	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:229)
17:41:04.007691 [error] [MainThread]:   	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:100)
17:41:04.008052 [error] [MainThread]:   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
17:41:04.008396 [error] [MainThread]:   	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
17:41:04.017237 [error] [MainThread]:   	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:615)
17:41:04.017927 [error] [MainThread]:   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
17:41:04.018338 [error] [MainThread]:   	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:610)
17:41:04.018671 [error] [MainThread]:   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:41:04.019077 [error] [MainThread]:   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:41:04.019552 [error] [MainThread]:   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:41:04.020243 [error] [MainThread]:   	at java.lang.reflect.Method.invoke(Method.java:498)
17:41:04.020623 [error] [MainThread]:   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
17:41:04.021027 [error] [MainThread]:   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
17:41:04.021671 [error] [MainThread]:   	at py4j.Gateway.invoke(Gateway.java:282)
17:41:04.022133 [error] [MainThread]:   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
17:41:04.022708 [error] [MainThread]:   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
17:41:04.023158 [error] [MainThread]:   	at py4j.GatewayConnection.run(GatewayConnection.java:238)
17:41:04.023506 [error] [MainThread]:   	at java.lang.Thread.run(Thread.java:750)
17:41:04.023841 [error] [MainThread]:
17:41:04.024171 [error] [MainThread]:   compiled SQL at target/run/lakehouse_spark/models/test_hudi/test_hudi__append.sql
17:41:04.024541 [info ] [MainThread]:
17:41:04.024925 [info ] [MainThread]: Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
17:41:04.025461 [debug] [MainThread]: Flushing usage events
17:41:04.026044 [debug] [MainThread]: Glue adapter: cleanup called
```

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.1.0
  - latest:    1.1.0 - Up to date!

Plugins:
  - spark: 1.1.0 - Up to date!
```

**The operating system you're using:**
MacOs 12.4

**The output of `python --version`:**
Python 3.7.9

**Comment by menuetb** [comment]
For the moment, the Hudi feature has been tested in Glue 2.0 (this adapter with Hudi and Glue 3 is on the roadmap but not yet available).
To make it works with Glue 2.0, you need to add extra jars in your adapter configuration.
You can use the following jars (they are public) to make a test:
extra_jars: "s3://aws-bigdata-blog/artifacts/hudi-on-glue/Dependencies/Jars/hudi-spark.jar,s3://aws-bigdata-blog/artifacts/hudi-on-glue/Dependencies/Jars/spark-avro_2.11-2.4.4.jar"

**Comment by mattssll** [comment]
@menuetb hi, since you mentioned you have experience in the issue, I'm facing it in:
```
Core:
  - installed: 1.3.0
  - latest:    1.3.0 - Up to date!

Plugins:
  - spark: 1.3.0 - Up to date!

dbt-glue==0.3.4
```
I also tried version 0.2.14 which is the latest 2.2x there is and I still get the same issue:
`org.apache.hudi.exception.HoodieException: 'hoodie.table.name' must be set
`

Wondering if you could perhaps help me out with this one?
Using glue 3.0, my glue connection is working as in a jupyter notebook I can create tables using the same connection.

Thanks!
