### ISSUE TITLE
New columns (on schema change) not supported when working with hudi/incremental

### ISSUE THREAD

**Issue by nicor88** [aws-samples/dbt-glue#92]
### Describe the bug
Adding new columns when working with hudi/incremental lead to some issues.
### Steps To Reproduce
Create a model like this:

```
{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='user_id',
	partition_by=['status'],
    file_format='hudi'
) }}

WITH data AS (
	SELECT 'A' AS user_id, 'active' AS status, 'pi' AS name
	UNION ALL
	SELECT 'B' AS user_id, 'active' AS status, 'sh' AS name
	UNION ALL
	SELECT 'C' AS user_id, 'active' AS status, 'zh' AS name
)

SELECT
	user_id,
	status,
	name,
	current_timestamp() AS inserted_at
FROM data
```
run the model. Then change the model to:
```
{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='user_id',
	partition_by=['status'],
    file_format='hudi'
) }}

WITH data AS (
	SELECT 'A' AS user_id, 'active' AS status, 'pi' AS name, 'test' AS col_a
	UNION ALL
	SELECT 'B' AS user_id, 'active' AS status, 'sh' AS name, 'test' AS col_a
	UNION ALL
	SELECT 'C' AS user_id, 'active' AS status, 'zh' AS name, 'test' AS col_a
)

SELECT
	user_id,
	status,
	name,
        col_a,
	current_timestamp() AS inserted_at
FROM data
```
After running the model I' getting this error:

```
Caused by: java.io.IOException: Required column is missing in data file. Col: [col_a]
        at org.apache.spark.sql.execution.datasources.parquet.VectorizedParquetRecordReader.validateRequestedSchemaIsSupported(VectorizedParquetRecordReader.java:331)
        at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat.$anonfun$buildPrefetcherWithPartitionValues$1(ParquetFileFormat.scala:543)
        at org.apache.spark.sql.execution.datasources.AsyncFileDownloader.org$apache$spark$sql$execution$datasources$AsyncFileDownloader$$downloadFile(AsyncFileDownloader.scala:93)
        at org.apache.spark.sql.execution.datasources.AsyncFileDownloader$$anon$1.call(AsyncFileDownloader.scala:73)
        at org.apache.spark.sql.execution.datasources.AsyncFileDownloader$$anon$1.call(AsyncFileDownloader.scala:72)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more

14:49:22  1 of 1 ERROR creating incremental model lakehouse_silver.test_hudi ............. [ERROR in 56.69s]
14:49:22  
14:49:22  Finished running 1 incremental model in 0 hours 1 minutes and 31.32 seconds (91.32s).
14:49:23  
14:49:23  Completed with 1 error and 0 warnings:
14:49:23  
14:49:23  Database Error in model test_hudi (models/silver/test_hudi.sql)
14:49:23    Glue cursor returned `error` for statement None for code SqlWrapper2.execute('''/* {"app": "dbt", "dbt_version": "1.2.1", "profile_name": "glue_lakehouse", "target_name": "dev", "node_id": "model.lakehouse.test_hudi"} */
14:49:23    select * from lakehouse_silver.test_hudi limit 1 '''), Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
14:49:23    : org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 57.0 failed 4 times, most recent failure: Lost task 1.3 in stage 57.0 (TID 397) (172.36.209.233 executor 2): org.apache.spark.sql.execution.datasources.FileDownloadException: Failed to download file path: s3://nicor88-lakehouse/lakehouse_silver/test_hudi/changed/1c2f729b-e21f-4bdd-a62f-76372dcc9fd9-0_2-41-355_20221014144605641.parquet, range: 0-432654, partition values: [changed], isDataPresent: false, eTag: f2e1d7c8388a7d555915c21cdd27c442
14:49:23        at org.apache.spark.sql.execution.datasources.AsyncFileDownloader.next(AsyncFileDownloader.scala:142)
14:49:23        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.getNextFile(FileScanRDD.scala:279)
14:49:23        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:201)
14:49:23        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:159)
14:49:23        at org.apache.spark.sql.execution.FileSourceScanExec$$anon$1.hasNext(DataSourceScanExec.scala:606)
14:49:23        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.columnartorow_nextBatch_0$(Unknown Source)
14:49:23        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
14:49:23        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
14:49:23        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
14:49:23        at scala.collection.Iterator$SliceIterator.hasNext(Iterator.scala:262)
14:49:23        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:454)
14:49:23        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:133)
14:49:23        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
14:49:23        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
14:49:23        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
14:49:23        at org.apache.spark.scheduler.Task.run(Task.scala:131)
14:49:23        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
14:49:23        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
14:49:23        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
14:49:23        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:49:23        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:49:23        at java.lang.Thread.run(Thread.java:750)
14:49:23    Caused by: java.io.IOException: Required column is missing in data file. Col: [col_a]
14:49:23        at org.apache.spark.sql.execution.datasources.parquet.VectorizedParquetRecordReader.validateRequestedSchemaIsSupported(VectorizedParquetRecordReader.java:331)
14:49:23        at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat.$anonfun$buildPrefetcherWithPartitionValues$1(ParquetFileFormat.scala:543)
14:49:23        at org.apache.spark.sql.execution.datasources.AsyncFileDownloader.org$apache$spark$sql$execution$datasources$AsyncFileDownloader$$downloadFile(AsyncFileDownloader.scala:93)
14:49:23        at org.apache.spark.sql.execution.datasources.AsyncFileDownloader$$anon$1.call(AsyncFileDownloader.scala:73)
14:49:23        at org.apache.spark.sql.execution.datasources.AsyncFileDownloader$$anon$1.call(AsyncFileDownloader.scala:72)
14:49:23        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
14:49:23        ... 3 more
14:49:23    
14:49:23    Driver stacktrace:
14:49:23        at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2465)
14:49:23        at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2414)
14:49:23        at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2413)
14:49:23        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
14:49:23        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
14:49:23        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
14:49:23        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2413)
14:49:23        at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1124)
14:49:23        at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1124)
14:49:23        at scala.Option.foreach(Option.scala:257)
14:49:23        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1124)
14:49:23        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2679)
14:49:23        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2621)
14:49:23        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2610)
14:49:23        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
14:49:23        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:914)
14:49:23        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2238)
14:49:23        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2259)
14:49:23        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2278)
14:49:23        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2303)
14:49:23        at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1030)
14:49:23        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
14:49:23        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
14:49:23        at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
14:49:23        at org.apache.spark.rdd.RDD.collect(RDD.scala:1029)
14:49:23        at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:180)
14:49:23        at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
14:49:23        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:49:23        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:49:23        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:49:23        at java.lang.reflect.Method.invoke(Method.java:498)
14:49:23        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
14:49:23        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
14:49:23        at py4j.Gateway.invoke(Gateway.java:282)
14:49:23        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
14:49:23        at py4j.commands.CallCommand.execute(CallCommand.java:79)
14:49:23        at py4j.GatewayConnection.run(GatewayConnection.java:238)
14:49:23        at java.lang.Thread.run(Thread.java:750)
14:49:23    Caused by: org.apache.spark.sql.execution.datasources.FileDownloadException: Failed to download file path: s3://grover-eu-central-1-dev-data-lakehouse/lakehouse_silver/test_hudi/changed/1c2f729b-e21f-4bdd-a62f-76372dcc9fd9-0_2-41-355_20221014144605641.parquet, range: 0-432654, partition values: [changed], isDataPresent: false, eTag: f2e1d7c8388a7d555915c21cdd27c442
14:49:23        at org.apache.spark.sql.execution.datasources.AsyncFileDownloader.next(AsyncFileDownloader.scala:142)
14:49:23        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.getNextFile(FileScanRDD.scala:279)
14:49:23        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:201)
14:49:23        at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:159)
14:49:23        at org.apache.spark.sql.execution.FileSourceScanExec$$anon$1.hasNext(DataSourceScanExec.scala:606)
14:49:23        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.columnartorow_nextBatch_0$(Unknown Source)
14:49:23        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
14:49:23        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
14:49:23        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
14:49:23        at scala.collection.Iterator$SliceIterator.hasNext(Iterator.scala:262)
14:49:23        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:454)
14:49:23        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:133)
14:49:23        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
14:49:23        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
14:49:23        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
14:49:23        at org.apache.spark.scheduler.Task.run(Task.scala:131)
14:49:23        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
14:49:23        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
14:49:23        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
14:49:23        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:49:23        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:49:23        ... 1 more
14:49:23    Caused by: java.io.IOException: Required column is missing in data file. Col: [col_a]
14:49:23        at org.apache.spark.sql.execution.datasources.parquet.VectorizedParquetRecordReader.validateRequestedSchemaIsSupported(VectorizedParquetRecordReader.java:331)
14:49:23        at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat.$anonfun$buildPrefetcherWithPartitionValues$1(ParquetFileFormat.scala:543)
14:49:23        at org.apache.spark.sql.execution.datasources.AsyncFileDownloader.org$apache$spark$sql$execution$datasources$AsyncFileDownloader$$downloadFile(AsyncFileDownloader.scala:93)
14:49:23        at org.apache.spark.sql.execution.datasources.AsyncFileDownloader$$anon$1.call(AsyncFileDownloader.scala:73)
14:49:23        at org.apache.spark.sql.execution.datasources.AsyncFileDownloader$$anon$1.call(AsyncFileDownloader.scala:72)
14:49:23        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
14:49:23        ... 3 more
14:49:23    
14:49:23    compiled SQL at target/run/lakehouse/models/silver/test_hudi.sql
14:49:23  
14:49:23  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1

```
As workaround, if I drop the table from glue, and re-run the model it works. But imagine a scenario where analysts add a new field, this will lead to easily braking behavior.

### Expected behavior
New col_a, added in the 2nd run will be added to the table.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.2.1
  - latest:    1.3.0 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - spark: 1.2.0 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

**The operating system you're using:** MacOS BigSur

**The output of `python --version`:** 3.9.6

### Additional context
> This could be a limitation of using hudi, as doesn't support schema changes.
The above seems not correct as schema changes seems supported. See [here](https://hudi.apache.org/docs/schema_evolution/)

**Comment by l-jhon** [comment]
I'm using dbt-glue adapter to write hudi table and to add new columns during the incremental process I added the config `on_schema_change`, and it works for me.

```
{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='user_id',
	partition_by=['status'],
	on_schema_change='append_new_columns',
    file_format='hudi'
) }}
```

**Comment by nicor88** [comment]
@l-jhon I was not aware of that feature. I will try out.

**Comment by nicor88** [comment]
@l-jhon somehow I got the same issue, but if I do a full-refresh or if I update all the records seems working. I think that then is fine. Are you doing full refresh to make this working??

**Comment by l-jhon** [comment]
> 

Let me see here, I remember that I'm running without the full refresh.

**Comment by l-jhon** [comment]
@nicor88 I reran it, and it worked without --full-refresh.

**Comment by nicor88** [comment]
Somehow didn't work for me, are you adding new columns?? I mean if I don't add new columns works for me too, as far as I add new columns, it breaks.

**Comment by l-jhon** [comment]
I ran the same model that you shared.

The first model that I ran:
```
{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='user_id',
	partition_by=['status'],
	on_schema_change='append_new_columns',
    file_format='hudi'
) }}

WITH data AS (
	SELECT 'A' AS user_id, 'active' AS status, 'pi' AS name
	UNION ALL
	SELECT 'B' AS user_id, 'active' AS status, 'sh' AS name
	UNION ALL
	SELECT 'C' AS user_id, 'active' AS status, 'zh' AS name
)

SELECT
	user_id,
	status,
	name,
	current_timestamp() AS inserted_at
FROM data
```

Then I ran the model change:
```
{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='user_id',
	partition_by=['status'],
	on_schema_change='append_new_columns',
    file_format='hudi'
) }}

WITH data AS (
	SELECT 'A' AS user_id, 'active' AS status, 'pi' AS name, 'test' AS col_a
	UNION ALL
	SELECT 'B' AS user_id, 'active' AS status, 'sh' AS name, 'test' AS col_a
	UNION ALL
	SELECT 'C' AS user_id, 'active' AS status, 'zh' AS name, 'test' AS col_a
)

SELECT
	user_id,
	status,
	name,
        col_a,
	current_timestamp() AS inserted_at
FROM data
```

What Hudi version are you using? I'm using the 0.12

**Comment by nicor88** [comment]
Interesting, I'm using the connector from the marketplace `Apache Hudi Connector 0.10.1 for AWS Glue 3.0` Might be related to that. Do you have some docs to share on how to use the a more recent version??

**Comment by l-jhon** [comment]
Oh I see! Yes, you just need to add the jar file in the `extra_jars` inside the profiles.yml, let me share with you:

```
dbt_glue_models:
    target: dev
    outputs:
      dev_stage:
        type: glue
        role_arn: arn:aws:iam::{aws_account}:role/GlueInteractiveSessionRole
        region: {region}
        workers: 2
        worker_type: G.025X
        database: awsdatacatalog
        schema: dev
        session_provisioning_timeout_in_seconds: 240
        idle_timeout: 60
        query_timeout_in_seconds: 300
        location: s3://{bucket}/stage/
        glue_version: "3.0"
        extra_jars: s3://{bucket}/configs/jars/hudi-utilities-bundle_2.12-0.12.1.jar,s3://{bucket}/configs/jars/hudi-spark3.1-bundle_2.12-0.12.1.jar,s3://{bucket}/configs/jars/spark-avro_2.12-3.2.2.jar,s3://{bucket}/configs/jars/calcite-core-1.32.0.jar
        conf: "spark.serializer=org.apache.spark.serializer.KryoSerializer"
```

**Comment by nicor88** [comment]
Lovely, thanks for that, I'm testing that again and then share the result with you. I think that you spot it, it's just due to hudi version!

**Comment by nicor88** [comment]
@l-jhon ok, I was able to add the new libs but still the same issue. 
if you run the models as here https://github.com/aws-samples/dbt-glue/issues/92#issuecomment-1289461258 as the 2nd run touch all the columns (so act as a full-refresh) works from me too. But if I just do this:

```
{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='user_id',
	partition_by=['status'],
	on_schema_change='append_new_columns',
    file_format='hudi'
) }}

WITH data AS (
	SELECT 'A' AS user_id, 'active' AS status, 'pi' AS name, 'test' AS col_a
	UNION ALL
	SELECT 'B' AS user_id, 'active' AS status, 'sh' AS name, 'test' AS col_a
	UNION ALL
	SELECT 'C' AS user_id, 'active' AS status, 'zh' AS name, 'test' AS col_a
)

SELECT
	user_id,
	status,
	name,
        col_a,
	current_timestamp() AS inserted_at
FROM data
where user_id='C'
```
e.g. add the new column only from new data, that will still give you the issue above.

As adding a new column imply running a full-refresh, I guess that we can close this one, this means that each time that we add a new column I will force a full-refresh.

**Comment by l-jhon** [comment]
I got it! 
Yes, I guess full-refresh is great to solve this problem :D

**Comment by nicor88** [comment]
Closing this one, as for new columns we need `--full-refresh` or  full_refresh=True
